// src/app/layout.js
import { Montserrat, Roboto } from 'next/font/google'; // Importation des nouvelles polices
import "./globals.css";

// 1. Définition des polices
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat', // Notre variable pour les titres (font-titre)
});

const roboto = Roboto({
  weight: ['400', '700'], // Charger les styles nécessaires
  subsets: ['latin'],
  variable: '--font-roboto', // Notre variable pour le corps (font-corps)
});

export const metadata = {
  title: "Everlast Windows & Doors | Interplast Quality",
  description: "The right choice for uPVC windows and doors. Beauty, Durability, Safety.",
};

export default function RootLayout({ children }) {
  return (
    // 2. Application des classes globales sur le body
    <html lang="en">
      <body className={`${montserrat.variable} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
